package br.com.luizrcs.correiostracker.ui.theme

import androidx.compose.ui.graphics.*

val md_theme_light_primary = Color(0xFF795900)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFffdf99)
val md_theme_light_onPrimaryContainer = Color(0xFF261a00)
val md_theme_light_secondary = Color(0xFF2458c4)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFdae2ff)
val md_theme_light_onSecondaryContainer = Color(0xFF00174b)
val md_theme_light_tertiary = Color(0xFF3a5ba8)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFd9e2ff)
val md_theme_light_onTertiaryContainer = Color(0xFF00184a)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFfffbf7)
val md_theme_light_onBackground = Color(0xFF1d1b16)
val md_theme_light_surface = Color(0xFFfffbf7)
val md_theme_light_onSurface = Color(0xFF1d1b16)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF49454F)
val md_theme_light_outline = Color(0xFF79747E)
val md_theme_light_inverseOnSurface = Color(0xFFf6f0e7)
val md_theme_light_inverseSurface = Color(0xFF33302a)
val md_theme_light_inversePrimary = Color(0xFFfabd00)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFfabd00)
val md_theme_dark_onPrimary = Color(0xFF402d00)
val md_theme_dark_primaryContainer = Color(0xFF5c4300)
val md_theme_dark_onPrimaryContainer = Color(0xFFffdf99)
val md_theme_dark_secondary = Color(0xFFb1c5ff)
val md_theme_dark_onSecondary = Color(0xFF002a78)
val md_theme_dark_secondaryContainer = Color(0xFF003ea7)
val md_theme_dark_onSecondaryContainer = Color(0xFFdae2ff)
val md_theme_dark_tertiary = Color(0xFFb0c5ff)
val md_theme_dark_onTertiary = Color(0xFF002b76)
val md_theme_dark_tertiaryContainer = Color(0xFF1e4390)
val md_theme_dark_onTertiaryContainer = Color(0xFFd9e2ff)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF1d1b16)
val md_theme_dark_onBackground = Color(0xFFe8e2d9)
val md_theme_dark_surface = Color(0xFF1d1b16)
val md_theme_dark_onSurface = Color(0xFFe8e2d9)
val md_theme_dark_surfaceVariant = Color(0xFF49454F)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_inverseOnSurface = Color(0xFF1d1b16)
val md_theme_dark_inverseSurface = Color(0xFFe8e2d9)
val md_theme_dark_inversePrimary = Color(0xFF795900)
val md_theme_dark_shadow = Color(0xFF000000)

object ParcelColors {
	val Red = Color(0xFFF44336)
	val Pink = Color(0xFFE91E63)
	val Purple = Color(0xFF9C27B0)
	val Indigo = Color(0xFF3F51B5)
	val Blue = Color(0xFF2196F3)
	val Cyan = Color(0xFF00BCD4)
	val Teal = Color(0xFF009688)
	val Green = Color(0xFF4CAF50)
	val Lime = Color(0xFFCDDC39)
	val Yellow = Color(0xFFFFEB3B)
	val Amber = Color(0xFFFFC107)
	val Orange = Color(0xFFFF9800)
	val Brown = Color(0xFF795548)
}